rewrite ^/rubygems/(.*)$ /$1 break;

proxy_pass https://rubygems_worker;

proxy_set_header Host              rubygems-proxy.gdutnic.com;
proxy_set_header X-Real-IP         $remote_addr;
proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $scheme;

proxy_ssl_server_name on;
proxy_ssl_name        rubygems-proxy.gdutnic.com;

proxy_cache             cache_rubygems;
proxy_cache_key         "$scheme$request_method$host$request_uri";
proxy_cache_use_stale   error timeout updating;
